version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./restaurant
    ports:
      - 8000:8000
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend/
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - api