version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./restaurant
    volumes:
      - ./restaurant/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}