# Generated by Django 4.0.4 on 2022-05-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('item', 'order')},
        ),
    ]
